spring:
  application:
    name: api-suministros
  datasource:
    url: jdbc:oracle:thin:@(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.sa-santiago-1.oraclecloud.com))(connect_data=(service_name=gd31f25638637e7_bbdddsy1103_medium.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
    username: ADMIN
    password: Estudiantes2026Duoc //cambiar
    driver-class-name: oracle.jdbc.OracleDriver
    jpa:
      database-platform: org.hibernate.dialect.OracleDialect
      hibernate:
        ddl-auto: validate
      show-sql: true
server:
  port: 21300